### ISSUE TITLE
Gem 1.07 fails in Redmine 3.3

### ISSUE THREAD

**Issue by jdkemme** [easyredmine/redmine_extensions#2]
```
NoMethodError: undefined method `prepend' for #<Class:0x00000004650870>
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/activerecord-4.2.6/lib/active_record/dynamic_matchers.rb:26:in `method_missing'
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/redmine_extensions-0.1.07/lib/redmine_extensions/easy_query_adapter.rb:174:in `<top (required)>'
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
/home/redmine/.rvm/gems/ruby-1.9.3-p551/gems/redmine_extensions-0.1.07/lib/redmine_extensions/engine.rb:76:in `block in <class:Engine>'
```

**Comment by ezr-ondrej** [comment]
yep, it has ruby v 2.0 dependency now...

**Comment by jdkemme** [comment]
Thank you, I see the problem- Easy gantt plugin v1.5 did not specify a version on the redmine_extensions gem, so there was no version in the gemfile.lock.  I've edited the Gemfile to pin to 0.1.05 until we can upgrade ruby.

```
if !Dir.exist?(File.expand_path('../../easyproject', __FILE__))
  gem 'redmine_extensions', '0.1.05'  
end
```
